### ISSUE TITLE
Time picker icon causes original dialog to disappear.

### ISSUE THREAD

**Issue by garretwilson** [classlinkinc/angular-material-time-picker#1]
I'm trying to use the time picker inside an `$mdDialog`, but when the user clicks the clock icon, the original dialog disappears and a new clock picker comes up. (An error then occurs: `Cannot read property 'getHours' of undefined)`.

Did you perhaps forget to use `multiple` when pulling up the clock dialog?

https://material.angularjs.org/latest/api/service/$mdDialog#multiple-dialogs

This is a huge issue. As a workaround, is there a way I can at least turn off the clock icon so that users won't try to click it, until this is fixed? Thanks.

**Comment by Andreasbaaserud** [comment]
This issue is connected to PR https://github.com/classlinkinc/angular-material-time-picker/pull/9
