### ISSUE TITLE
TypeError: Cannot read property 'getHours' of undefined

### ISSUE THREAD

**Issue by FelipeAguayo** [classlinkinc/angular-material-time-picker#10]
I'm trying to use the time picker in my project. I completed all the instructions to add, but at the moment of opening the dialog, I get the following error:

```
TypeError: Cannot read property 'getHours' of undefined
    at controller.init 
    at new controller 
    at Object.invoke 
```
OBS: I am using angularjs 1.6.4.

**Comment by Andreasbaaserud** [comment]
I can't answer you why this happens on 1.6.4, I guess it's the same for 1.6.x.

FYI: I have tested this library on 1.5.9, works as it should.

**Comment by mtrogers** [comment]
Does [this](https://stackoverflow.com/questions/42426006/angular-upgrade-1-5-to-1-6-causes-directive-scope-bindings-to-become-undefined) shed any light?

**Comment by FelipeAguayo** [comment]
@mtrogers Yes, thank you very much, this helped me a lot. I applied the following solution and it worked:
```javascript
angular.module('app.core')
  .config(['$compileProvider', compileProviderConfig])
;

function compileProviderConfig($compileProvider){
  $compileProvider.preAssignBindingsEnabled(true);
}
```
I hope that in the future there may be a release that includes a native solution to the problem in the component.

**Comment by mtrogers** [comment]
Happy to help
