### ISSUE TITLE
form in the template?

### ISSUE THREAD

**Issue by cstephe** [classlinkinc/angular-material-time-picker#18]
Why is there a form element in the template? This ends up making it useless unless used only by itself.   an ng-form would be a little more understandable since they can be nested but even then I don't see the point.   But maybe I'm missing something?

**Comment by Andreasbaaserud** [comment]
I agree the form should be replaced with ng-form.
With form / ng-form you can use the angularjs built-in form validators.
https://docs.angularjs.org/guide/forms

**Comment by zscronce** [comment]
Opened a PR that will hopefully resolve this. #21

**Comment by Andreasbaaserud** [comment]
I will test it today

**Comment by Andreasbaaserud** [comment]
Resolved in release 1.0.7
