### ISSUE TITLE
Meridiem Selector & clock button appear editable when read-only="true"

### ISSUE THREAD

**Issue by cbacon91** [classlinkinc/angular-material-time-picker#19]
When the meridiem selector is available but the directive is marked as `read-only`, the user can still click on the meridiem selector, but not make any choices. It would look better if this was not clickable at all - `md-select` has a `disabled` option to disable this.

Additionally, when the directive is in `read-only`, the clock icon has `cursor: pointer`, even though it's not editable. This should probably be set to `cursor: default` to stay consistent with `md-datepicker`.

Codepen of the issues: 

https://codepen.io/cbacon91/pen/wqBrgY

**Comment by Andreasbaaserud** [comment]
Good points, I will apply the fixes below for release 1.0.8
- [ ] Append ng-disabled to md-select in mdMeridiem directive, no need for ng-disabled on md-option element
- [ ] set cursor: default when directive is in read-only
