### ISSUE TITLE
Time values do not appear in fields.

### ISSUE THREAD

**Issue by garretwilson** [classlinkinc/angular-material-time-picker#2]
I'm using Angular 1.6.4 with Angular Material 1.1.3. I linked to `md-time-picker.css` and included the script `md-time-picker.js`. Then in my dialog module I indicated a dependency of `"md.time.picker"` (I found this from the source code; your readme doesn't seem to have the correct value). In my controller I added a date:

```javascript
this.foo=new Date();
```

And then in my dialog template I added the control (using controller as `dialog`):

```html
<md-input-container>
  <label>Time</label>
  <md-time-picker ng-model="dialog.foo"></md-time-picker>
</md-input-container>
```

The control shows up, but all the fields are blank. If I click in one of the fields, the value shows up, but when I move to another field, the value disappears again. It appears as if the field is blank. If I erase e.g. the hours, "HH" shows upon the field as expected, and the control is marked as invalid, as expected.

**Comment by pritin-tyagaraj** [comment]
I had the exact same problem when I placed the `<md-time-picker>` within an `<md-input-container>`. Once I moved the time picker out of the input container, it was OK.

**Comment by garretwilson** [comment]
I abandoned this library after running into this issue and #1. Now I'm just using `<input>` with the `time` type. I hadn't realized that modern browsers offer a time picker already that works just fine for my needs.

**Comment by Andreasbaaserud** [comment]
I think this is resolved. Closing for now.
