### ISSUE TITLE
npm install version 1.0.7

### ISSUE THREAD

**Issue by Geoffrey-Dere** [classlinkinc/angular-material-time-picker#23]
Hello,

I can't install the version 1.0.7 (No matching version found for angular-material-time-picker@^1.0.7)
Can you do someting? thx

And good job for you time picker :+1:

**Comment by Andreasbaaserud** [comment]
I am afraid it's not yet updated to 1.0.7 in npm database. I am requesting the owner.

**Comment by Andreasbaaserud** [comment]
The npm repository has been updated to 1.0.7 and you should be able to use npm install angular-material-time-picker in order to retriev version 1.0.7
